# Generated by Django 5.2.7 on 2025-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS_DATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Contact_Number', models.CharField(max_length=14)),
                ('About_Project', models.CharField(max_length=1000)),
            ],
        ),
    ]
